# Welcome to Jekyll!

title: Energize
description: Mock API Platform
url: "https://vinctustech.github.io/energize/"
email: edadma@gmail.com
baseurl: "/energize"
github_username:  edadma
timezone: America/Montreal

# Build settings
markdown: kramdown
theme: jekyll-theme-cayman
plugins:
  - jekyll-redirect-from
exclude:
  - Gemfile
  - Gemfile.lock
defaults:
- scope:
    path: docs
    type: pages
  values:
    layout: docs
- scope:
    path: tutorial
    type: pages
  values:
    layout: tutorial